In [20]:
%load_ext autoreload
%autoreload 2

In [21]:
import numpy as np
import pandas as pd
from tqdm import tqdm

In [22]:
import factor_design
import utils

In [23]:
all_data = pd.read_csv('train.csv')

In [60]:
test_data = all_data.iloc[-880000:,:]

In [24]:
all_data['slice_index'] = all_data['date_id'].astype(str) + '_' + all_data['seconds_in_bucket'].astype(str)  # 3 seconds
all_data_dic_sorted = all_data.drop(columns=['target']).groupby('slice_index').agg(lambda x: x.tolist()).to_dict('index')  # 1min

  0%|          | 0/12 [09:03<?, ?it/s]


In [61]:
test_data['slice_index'] = test_data['date_id'].astype(str) + '_' + test_data['seconds_in_bucket'].astype(str)  # 3 seconds
test_data_dic_sorted = test_data.drop(columns=['target']).groupby('slice_index').agg(lambda x: x.tolist()).to_dict('index')  # 1min

C:\Users\kevin\AppData\Local\Temp\ipykernel_22028\1042900487.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data['slice_index'] = test_data['date_id'].astype(str) + '_' + test_data['seconds_in_bucket'].astype(str)  # 3 seconds


In [62]:
utils.dump_json(test_data_dic_sorted, 'test_data_dic_sorted.json')

In [25]:
col2index_map = utils.load_json('col2index_map.json')

In [26]:
def origin_seconds_in_bucket(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return -current_data[:, col2index_map['seconds_in_bucket']]


def origin_imbalance_size(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return current_data[:, col2index_map['imbalance_size']]


def origin_imbalance_buy_sell_flag(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return current_data[:, col2index_map['imbalance_buy_sell_flag']]


def origin_reference_price(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return -current_data[:, col2index_map['reference_price']]


def origin_matched_size(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return current_data[:, col2index_map['matched_size']]


def origin_far_price(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return current_data[:, col2index_map['far_price']]


def origin_near_price(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return current_data[:, col2index_map['near_price']]


def origin_bid_price(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return -current_data[:, col2index_map['bid_price']]


def origin_bid_size(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return -current_data[:, col2index_map['bid_size']]


def origin_ask_price(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return -current_data[:, col2index_map['ask_price']]


def origin_ask_size(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return current_data[:, col2index_map['ask_size']]


def origin_wap(current_data: dict, hist_list=[]) -> np.ndarray:
    current_data = np.array(list(current_data.values()), dtype=float).T
    current_data = np.nan_to_num(current_data)
    return -current_data[:, col2index_map['wap']]

In [27]:
# write a list of all factors with string
factor_list = [
    'origin_seconds_in_bucket',
    'origin_imbalance_size',
    'origin_imbalance_buy_sell_flag',
    'origin_reference_price',
    'origin_matched_size',
    'origin_far_price',
    'origin_near_price',
    'origin_bid_price',
    'origin_bid_size',
    'origin_ask_price',
    'origin_ask_size',
    'origin_wap',
]

In [34]:
# DO NOT MODIFY THE FOLLOWING CODE
# Run this cell once you want to calculate your factor values and prepare for the test of your factor performance!
new_factors = {factor_name: utils.flatten_factor_value(
    factor_design.run_factor_value(all_data_dic_sorted, eval(factor_name), factor_name), factor_name)[factor_name] for
               factor_name in tqdm(factor_list)}



  0%|          | 0/12 [00:00<?, ?it/s]

num_dates: 481
Start calculating factor origin_seconds_in_bucket
Finished calculating factor origin_seconds_in_bucket for 0 dates
Finished calculating factor origin_seconds_in_bucket for 100 dates
Finished calculating factor origin_seconds_in_bucket for 200 dates
Finished calculating factor origin_seconds_in_bucket for 300 dates
Finished calculating factor origin_seconds_in_bucket for 400 dates
Finished calculating factor origin_seconds_in_bucket for 480 dates
Accepted!!: Used 5.17 seconds for calculation factors. The limit is 300 seconds.




  8%|▊         | 1/12 [00:05<01:03,  5.81s/it]

num_dates: 481
Start calculating factor origin_imbalance_size
Finished calculating factor origin_imbalance_size for 0 dates
Finished calculating factor origin_imbalance_size for 100 dates
Finished calculating factor origin_imbalance_size for 200 dates
Finished calculating factor origin_imbalance_size for 300 dates
Finished calculating factor origin_imbalance_size for 400 dates
Finished calculating factor origin_imbalance_size for 480 dates
Accepted!!: Used 5.41 seconds for calculation factors. The limit is 300 seconds.




 17%|█▋        | 2/12 [00:12<01:00,  6.07s/it]

num_dates: 481
Start calculating factor origin_imbalance_buy_sell_flag
Finished calculating factor origin_imbalance_buy_sell_flag for 0 dates
Finished calculating factor origin_imbalance_buy_sell_flag for 100 dates
Finished calculating factor origin_imbalance_buy_sell_flag for 200 dates
Finished calculating factor origin_imbalance_buy_sell_flag for 300 dates
Finished calculating factor origin_imbalance_buy_sell_flag for 400 dates
Finished calculating factor origin_imbalance_buy_sell_flag for 480 dates
Accepted!!: Used 5.15 seconds for calculation factors. The limit is 300 seconds.




 25%|██▌       | 3/12 [00:18<00:54,  6.05s/it]

num_dates: 481
Start calculating factor origin_reference_price
Finished calculating factor origin_reference_price for 0 dates
Finished calculating factor origin_reference_price for 100 dates
Finished calculating factor origin_reference_price for 200 dates
Finished calculating factor origin_reference_price for 300 dates
Finished calculating factor origin_reference_price for 400 dates
Finished calculating factor origin_reference_price for 480 dates
Accepted!!: Used 4.87 seconds for calculation factors. The limit is 300 seconds.




 33%|███▎      | 4/12 [00:23<00:46,  5.83s/it]

num_dates: 481
Start calculating factor origin_matched_size
Finished calculating factor origin_matched_size for 0 dates
Finished calculating factor origin_matched_size for 100 dates
Finished calculating factor origin_matched_size for 200 dates
Finished calculating factor origin_matched_size for 300 dates
Finished calculating factor origin_matched_size for 400 dates
Finished calculating factor origin_matched_size for 480 dates
Accepted!!: Used 5.38 seconds for calculation factors. The limit is 300 seconds.




 42%|████▏     | 5/12 [00:29<00:41,  5.98s/it]

num_dates: 481
Start calculating factor origin_far_price
Finished calculating factor origin_far_price for 0 dates
Finished calculating factor origin_far_price for 100 dates
Finished calculating factor origin_far_price for 200 dates
Finished calculating factor origin_far_price for 300 dates
Finished calculating factor origin_far_price for 400 dates
Finished calculating factor origin_far_price for 480 dates
Accepted!!: Used 5.02 seconds for calculation factors. The limit is 300 seconds.




 50%|█████     | 6/12 [00:35<00:35,  5.91s/it]

num_dates: 481
Start calculating factor origin_near_price
Finished calculating factor origin_near_price for 0 dates
Finished calculating factor origin_near_price for 100 dates
Finished calculating factor origin_near_price for 200 dates
Finished calculating factor origin_near_price for 300 dates
Finished calculating factor origin_near_price for 400 dates
Finished calculating factor origin_near_price for 480 dates
Accepted!!: Used 5.42 seconds for calculation factors. The limit is 300 seconds.




 58%|█████▊    | 7/12 [00:41<00:30,  6.02s/it]

num_dates: 481
Start calculating factor origin_bid_price
Finished calculating factor origin_bid_price for 0 dates
Finished calculating factor origin_bid_price for 100 dates
Finished calculating factor origin_bid_price for 200 dates
Finished calculating factor origin_bid_price for 300 dates
Finished calculating factor origin_bid_price for 400 dates
Finished calculating factor origin_bid_price for 480 dates
Accepted!!: Used 5.06 seconds for calculation factors. The limit is 300 seconds.




 67%|██████▋   | 8/12 [00:47<00:23,  5.91s/it]

num_dates: 481
Start calculating factor origin_bid_size
Finished calculating factor origin_bid_size for 0 dates
Finished calculating factor origin_bid_size for 100 dates
Finished calculating factor origin_bid_size for 200 dates
Finished calculating factor origin_bid_size for 300 dates
Finished calculating factor origin_bid_size for 400 dates
Finished calculating factor origin_bid_size for 480 dates
Accepted!!: Used 5.02 seconds for calculation factors. The limit is 300 seconds.




 75%|███████▌  | 9/12 [00:53<00:17,  5.84s/it]

num_dates: 481
Start calculating factor origin_ask_price
Finished calculating factor origin_ask_price for 0 dates
Finished calculating factor origin_ask_price for 100 dates
Finished calculating factor origin_ask_price for 200 dates
Finished calculating factor origin_ask_price for 300 dates
Finished calculating factor origin_ask_price for 400 dates
Finished calculating factor origin_ask_price for 480 dates
Accepted!!: Used 5.01 seconds for calculation factors. The limit is 300 seconds.




 83%|████████▎ | 10/12 [00:58<00:11,  5.81s/it]

num_dates: 481
Start calculating factor origin_ask_size
Finished calculating factor origin_ask_size for 0 dates
Finished calculating factor origin_ask_size for 100 dates
Finished calculating factor origin_ask_size for 200 dates
Finished calculating factor origin_ask_size for 300 dates
Finished calculating factor origin_ask_size for 400 dates
Finished calculating factor origin_ask_size for 480 dates
Accepted!!: Used 5.72 seconds for calculation factors. The limit is 300 seconds.




 92%|█████████▏| 11/12 [01:05<00:06,  6.05s/it]

num_dates: 481
Start calculating factor origin_wap
Finished calculating factor origin_wap for 0 dates
Finished calculating factor origin_wap for 100 dates
Finished calculating factor origin_wap for 200 dates
Finished calculating factor origin_wap for 300 dates
Finished calculating factor origin_wap for 400 dates
Finished calculating factor origin_wap for 480 dates
Accepted!!: Used 4.88 seconds for calculation factors. The limit is 300 seconds.




100%|██████████| 12/12 [01:11<00:00,  5.92s/it]


In [35]:
new_factors['origin_seconds_in_bucket']

array([  -0.,   -0.,   -0., ..., -540., -540., -540.])

In [32]:
len(all_data)

5237980

In [42]:
train_data = pd.read_csv('../research_train_set.csv')

In [43]:
len(all_data)-len(train_data)

880000

In [44]:
test_existed_factor = pd.DataFrame(new_factors).iloc[-880000:,:].to_dict('list')

In [47]:
utils.dump_json(test_existed_factor, 'test_existed_factor.json')

In [49]:
target_on_test = np.load('target_on_test.npy')
target_on_test[np.isnan(target_on_test)] = 0

In [54]:
target_on_test

array([-1.3297796,  0.1502037,  2.7501583, ...,  1.1694431, -1.540184 ,
       -6.530285 ])

In [55]:
new_factors['origin_seconds_in_bucket']

array([  -0.,   -0.,   -0., ..., -540., -540., -540.])

In [56]:
factor_performance = {}
for keys, item in new_factors.items():
    factor_performance[keys] = np.corrcoef(item[-880000:], target_on_test)[0, 1]

In [59]:
utils.dump_json(factor_performance, 'factor_performance_test.json')